# Generated by Django 5.1.6 on 2025-07-20 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notice',
            name='is_admin',
            field=models.BooleanField(default=False),
        ),
    ]
