# Generated by Django 5.1.6 on 2025-07-20 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0002_notice_is_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='notice',
            name='is_html',
            field=models.BooleanField(default=False),
        ),
    ]
