# Generated by Django 5.1.6 on 2025-04-03 10:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='session',
            old_name='date_finished',
            new_name='finish_date',
        ),
        migrations.RenameField(
            model_name='session',
            old_name='date_started',
            new_name='start_date',
        ),
    ]
