# Generated by Django 5.1.6 on 2025-04-06 17:02

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_sessionranking'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='members',
            field=models.ManyToManyField(null=True, related_name='sessions', to=settings.AUTH_USER_MODEL),
        ),
    ]
