# Generated by Django 5.1.6 on 2025-07-11 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_session_members'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todo',
            name='deadline',
        ),
        migrations.AddField(
            model_name='todo',
            name='completed_on',
            field=models.DateField(blank=True, null=True),
        ),
    ]
