# Generated by Django 5.1.6 on 2025-07-11 17:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_remove_todo_deadline_todo_completed_on'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrackTodo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DateField(blank=True, null=True)),
                ('hours', models.FloatField(default=0.0)),
                ('todo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tracking', to='pages.todo')),
            ],
        ),
    ]
