# Generated by Django 5.1.6 on 2025-07-13 11:02

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0006_tracktodo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='tracktodo',
            name='hours_till_day',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='session',
            name='members',
            field=models.ManyToManyField(blank=True, related_name='sessions', to=settings.AUTH_USER_MODEL),
        ),
    ]
