# Generated by Django 5.1.6 on 2025-07-16 17:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0008_session_description'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sessionranking',
            options={'ordering': ['rank']},
        ),
        migrations.RemoveField(
            model_name='sessionranking',
            name='completed_todos_count',
        ),
        migrations.RemoveField(
            model_name='sessionranking',
            name='completion_time',
        ),
        migrations.RemoveField(
            model_name='sessionranking',
            name='total_todos_count',
        ),
        migrations.AddField(
            model_name='sessionranking',
            name='total_hours',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='sessionranking',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='session_rankings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='RoomRanking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.PositiveIntegerField()),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rankings', to='pages.room')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='room_rankings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['rank'],
                'unique_together': {('room', 'user')},
            },
        ),
    ]
