# Generated by Django 5.1.6 on 2025-07-16 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0009_alter_sessionranking_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='roomranking',
            name='total_hours',
            field=models.FloatField(default=0.0),
        ),
    ]
